services:
  postgres-auth:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupass
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth:/var/lib/postgresql/data
    networks:
      - edu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduuser -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-courses:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupass
      POSTGRES_DB: courses_db
    volumes:
      - postgres_courses:/var/lib/postgresql/data
    networks:
      - edu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduuser -d courses_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-enrollments:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: eduuser
      POSTGRES_PASSWORD: edupass
      POSTGRES_DB: enrollments_db
    volumes:
      - postgres_enrollments:/var/lib/postgresql/data
    networks:
      - edu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduuser -d enrollments_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-kong:
    image: postgres:16
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpassword
      POSTGRES_DB: kong
    volumes:
      - postgres_kong:/var/lib/postgresql/data
    networks:
      - edu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    depends_on:
      - postgres-kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpassword
    networks:
      - edu-net


  kong:
    image: kong:3.6
    depends_on:
      - auth-service
      - courses-service
      - enrollments-service
      - public-frontend
      - private-frontend
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpassword
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - edu-net
    restart: unless-stopped
  
  konga:
    image: pantsel/konga:latest
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=konga
    networks:
      - edu-net
    depends_on:
      - kong
    restart: unless-stopped

  auth-service:
    image: edu-platform-auth-service:1.0
    environment:
      PORT: 4001
      DATABASE_URL: postgresql://eduuser:edupass@postgres-auth:5432/auth_db
      JWT_SECRET: edu_jwt_secret_2026
    expose:
      - "4001"
    networks:
      - edu-net
    depends_on:
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped

  courses-service:
    image: edu-platform-courses-service:1.0
    environment:
      PORT: 4002
      DATABASE_URL: postgresql://eduuser:edupass@postgres-courses:5432/courses_db
    expose:
      - "4002"
    networks:
      - edu-net
    depends_on:
      postgres-courses:
        condition: service_healthy
    restart: unless-stopped

  enrollments-service:
    image: edu-platform-enrollments-service:1.0
    environment:
      PORT: 4003
      DATABASE_URL: postgresql://eduuser:edupass@postgres-enrollments:5432/enrollments_db
    expose:
      - "4003"
    networks:
      - edu-net
    depends_on:
      postgres-enrollments:
        condition: service_healthy
    restart: unless-stopped

  public-frontend:
    image: edu-platform-public-frontend:1.1
    expose:
      - "3000"
    networks:
      - edu-net
    restart: unless-stopped

  private-frontend:
    image: edu-platform-private-frontend:1.0
    expose:
      - "3000"
    networks:
      - edu-net
    restart: unless-stopped

volumes:
  postgres_auth:
  postgres_courses:
  postgres_enrollments:
  postgres_kong:

networks:
  edu-net:
    driver: bridge